parameters:
#    cb_client.example.class: CB\ClientBundle\Example

services:
#    cb_client.example:
#        class: %cb_client.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
