parameters:
    cb_client.oauthrequestor.class: CB\ClientBundle\Security\OAuthRequestor
    cb_client_oauth_user_grants.class: CB\ClientBundle\Security\OAuthUserGrants

services:
    cb_client.oauthrequestor:
        class: %cb_client.oauthrequestor.class%
        calls:
            - [setUserGrantsManager, ["@cb_client.oauth_user_grants"]]
            - [setBroswer, ["@buzz"]]
       # arguments: [@service_id, "plain_value", %parameter%]
    cb_client.oauth_user_grants:
        class: %cb_client_oauth_user_grants.class%